name: Update recommendations

on:
  schedule:
    - cron: "15 */8 * * 6-7"
    - cron: "55 5-20 * * 1-5"
jobs:
  build:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Update recommendations
      run: ./gradlew updateRecommendations
    - name: Run publish if necessary
      env: # Or as an environment variable
        GRGIT_USER: ${{ secrets.GRGIT_USER }}
      run: ./gradlew gitPublishPush
